/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Bulk update value list items API endpoint
 *   version: 2023-10-31
 */

import { z, lazySchema } from '@kbn/zod/v4';

import { ListItemId, ListItemValue, ListItemMetadata, ListVersionId } from '../model/list_common.gen';
import { ListItem } from '../model/list_schemas.gen';

export const BulkUpdateListItemsRequestBodyItem = lazySchema(() =>
  z.object({
    id: ListItemId,
    value: ListItemValue,
    meta: ListItemMetadata.optional(),
    _version: ListVersionId.optional(),
  })
);
export type BulkUpdateListItemsRequestBodyItem = z.infer<
  typeof BulkUpdateListItemsRequestBodyItem
>;

export const BulkUpdateListItemsRequestBody = lazySchema(() =>
  z.object({
    /**
     * Array of list items to update.
     */
    items: z.array(BulkUpdateListItemsRequestBodyItem).min(1).max(1000),
    /**
     * Determines when changes made by the request are made visible to search.
     */
    refresh: z.enum(['true', 'false', 'wait_for']).optional(),
  })
);
export type BulkUpdateListItemsRequestBody = z.infer<typeof BulkUpdateListItemsRequestBody>;
export type BulkUpdateListItemsRequestBodyInput = z.input<typeof BulkUpdateListItemsRequestBody>;

export const BulkUpdateListItemsResponse = lazySchema(() =>
  z.object({
    /**
     * Indicates whether any items failed to be updated.
     */
    errors: z.boolean(),
    /**
     * Number of items successfully updated.
     */
    updated_count: z.number().int(),
    /**
     * Number of items that failed to be updated.
     */
    error_count: z.number().int(),
    /**
     * Successfully updated list items.
     */
    items: z.array(ListItem),
    /**
     * Items that failed to be updated with error details.
     */
    error_items: z.array(
      z.object({
        /**
         * The index of the item in the original request array.
         */
        index: z.number().int(),
        /**
         * The id of the item that failed to be updated.
         */
        id: z.string(),
        error: z.object({
          status_code: z.number().int(),
          message: z.string(),
        }),
      })
    ),
  })
);
export type BulkUpdateListItemsResponse = z.infer<typeof BulkUpdateListItemsResponse>;
