/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Bulk create value list items API endpoint
 *   version: 2023-10-31
 */

import { z, lazySchema } from '@kbn/zod/v4';

import { ListId, ListItemValue, ListItemMetadata } from '../model/list_common.gen';
import { ListItem } from '../model/list_schemas.gen';

export const BulkCreateListItemsRequestBody = lazySchema(() =>
  z.object({
    list_id: ListId,
    /**
     * Array of values to create as list items.
     */
    value: z.array(ListItemValue).min(1).max(1000),
    meta: ListItemMetadata.optional(),
    /**
     * Determines when changes made by the request are made visible to search.
     */
    refresh: z.enum(['true', 'false', 'wait_for']).optional(),
  })
);
export type BulkCreateListItemsRequestBody = z.infer<typeof BulkCreateListItemsRequestBody>;
export type BulkCreateListItemsRequestBodyInput = z.input<typeof BulkCreateListItemsRequestBody>;

export const BulkCreateListItemsResponse = lazySchema(() =>
  z.object({
    /**
     * Indicates whether any items failed to be created.
     */
    errors: z.boolean(),
    /**
     * Number of items successfully created.
     */
    created_count: z.number().int(),
    /**
     * Number of items that failed to be created.
     */
    error_count: z.number().int(),
    /**
     * Successfully created list items.
     */
    items: z.array(ListItem),
    /**
     * Items that failed to be created with error details.
     */
    error_items: z.array(
      z.object({
        /**
         * The index of the item in the original request array.
         */
        index: z.number().int(),
        /**
         * The value that failed to be created.
         */
        value: z.string(),
        error: z.object({
          status_code: z.number().int(),
          message: z.string(),
        }),
      })
    ),
  })
);
export type BulkCreateListItemsResponse = z.infer<typeof BulkCreateListItemsResponse>;
